#ifndef USB_XHCI_REGISTERS_H
#define USB_XHCI_REGISTERS_H

#define XHCI_PCI_CLASS 0x0c
#define XHCI_PCI_SUBCLASS 0x03
#define XHCI_PCI_INTERFACE 0x30

#define XHCI_CAP_LENGTH 0x00
#define XHCI_CAP_VERSION_SHIFT 16
#define XHCI_CAP_SLOTS_PORTS 0x04
#define XHCI_CAP_SCRATCHPADS 0x08
#define XHCI_CAP_FEATURES 0x10
#define XHCI_CAP_DOORBELLS 0x14
#define XHCI_CAP_RUNTIME 0x18
#define XHCI_CAP_BYTES 0x20
#define XHCI_VERSION_MAJOR_SHIFT 8
#define XHCI_MAX_SLOTS_MASK 0xff
#define XHCI_MAX_INTERRUPTERS_SHIFT 8
#define XHCI_MAX_INTERRUPTERS_MASK 0x7ff
#define XHCI_MAX_PORTS_SHIFT 24
#define XHCI_SCRATCHPAD_HIGH_SHIFT 21
#define XHCI_SCRATCHPAD_LOW_SHIFT 27
#define XHCI_SCRATCHPAD_FIELD_MASK 0x1f
#define XHCI_SCRATCHPAD_HIGH_WEIGHT 5
#define XHCI_FEATURE_64_BIT (1u << 0)
#define XHCI_FEATURE_CONTEXT_64 (1u << 2)
#define XHCI_FEATURE_PORT_POWER (1u << 3)
#define XHCI_EXT_CAP_SHIFT 16
#define XHCI_EXT_CAP_DWORD_BYTES 4
#define XHCI_DOORBELL_OFFSET_MASK 0xfffffffc
#define XHCI_RUNTIME_OFFSET_MASK 0xffffffe0
#define XHCI_DOORBELL_BYTES 4

#define XHCI_EXT_ID_MASK 0xff
#define XHCI_EXT_NEXT_SHIFT 8
#define XHCI_EXT_NEXT_MASK 0xff
#define XHCI_EXT_LEGACY 1
#define XHCI_EXT_PROTOCOL 2
#define XHCI_LEGACY_BYTES 8
#define XHCI_LEGACY_BIOS_BYTE 2
#define XHCI_LEGACY_OS_BYTE 3
#define XHCI_LEGACY_OWNED 1
#define XHCI_LEGACY_CONTROL 4
#define XHCI_LEGACY_SMI_ENABLES ((1u << 0) | (1u << 4) | (7u << 13))
#define XHCI_LEGACY_W1C (7u << 29)
#define XHCI_LEGACY_RESERVED_ZERO (0xffu << 21)
#define XHCI_PROTOCOL_BYTES 16
#define XHCI_PROTOCOL_MAJOR_SHIFT 24
#define XHCI_PROTOCOL_MINOR_SHIFT 16
#define XHCI_PROTOCOL_NAME 0x20425355
#define XHCI_PROTOCOL_PORT_COUNT_SHIFT 8
#define XHCI_PROTOCOL_SPEED_COUNT_SHIFT 28
#define XHCI_PROTOCOL_SLOT_TYPE_MASK 0x1f

#define XHCI_OP_COMMAND 0x00
#define XHCI_OP_STATUS 0x04
#define XHCI_OP_PAGE_SIZE 0x08
#define XHCI_OP_NOTIFICATION 0x14
#define XHCI_OP_COMMAND_RING 0x18
#define XHCI_OP_DCBAA 0x30
#define XHCI_OP_CONFIG 0x38
#define XHCI_OP_BYTES 0x3c
#define XHCI_NOTIFICATION_MASK 0xffff
#define XHCI_CONFIG_SLOTS_MASK 0xff
#define XHCI_COMMAND_RUN (1u << 0)
#define XHCI_COMMAND_RESET (1u << 1)
#define XHCI_COMMAND_INTERRUPT (1u << 2)
#define XHCI_COMMAND_SYSTEM_ERROR (1u << 3)
#define XHCI_STATUS_HALTED (1u << 0)
#define XHCI_STATUS_SYSTEM_ERROR (1u << 2)
#define XHCI_STATUS_INTERRUPT (1u << 3)
#define XHCI_STATUS_PORT_CHANGE (1u << 4)
#define XHCI_STATUS_NOT_READY (1u << 11)
#define XHCI_STATUS_CONTROLLER_ERROR (1u << 12)
#define XHCI_PAGE_4K (1u << 0)
#define XHCI_PORTS_OFFSET 0x400
#define XHCI_PORT_BYTES 0x10
#define XHCI_PORT_CONNECTED (1u << 0)
#define XHCI_PORT_ENABLED (1u << 1)
#define XHCI_PORT_OVER_CURRENT (1u << 3)
#define XHCI_PORT_RESET (1u << 4)
#define XHCI_PORT_POWER (1u << 9)
#define XHCI_PORT_SPEED_SHIFT 10
#define XHCI_PORT_SPEED_MASK 0x0f
#define XHCI_PORT_INDICATOR_MASK (3u << 14)
#define XHCI_PORT_CONNECT_CHANGE (1u << 17)
#define XHCI_PORT_CHANGES (0x7fu << 17)
#define XHCI_PORT_WAKE_MASK (7u << 25)
#define XHCI_PORT_NEUTRAL (XHCI_PORT_POWER | XHCI_PORT_INDICATOR_MASK | XHCI_PORT_WAKE_MASK)

#define XHCI_INTERRUPTER_ZERO 0x20
#define XHCI_INTERRUPTER_BYTES 0x20
#define XHCI_INTR_MANAGEMENT 0x00
#define XHCI_INTR_MODERATION 0x04
#define XHCI_INTR_ERST_SIZE 0x08
#define XHCI_INTR_ERST_BASE 0x10
#define XHCI_INTR_DEQUEUE 0x18
#define XHCI_INTR_PENDING (1u << 0)
#define XHCI_INTR_ENABLE (1u << 1)
#define XHCI_ERST_SIZE_MASK 0xffff
#define XHCI_COMMAND_RING_PRESERVE 0x30
#define XHCI_ERST_BASE_PRESERVE 0x3f
#define XHCI_DEQUEUE_BUSY (1u << 3)

#define XHCI_TRB_BYTES 16
#define XHCI_TRB_CYCLE (1u << 0)
#define XHCI_TRB_TOGGLE_CYCLE (1u << 1)
#define XHCI_TRB_TYPE_SHIFT 10
#define XHCI_TRB_TYPE_MASK 0x3f
#define XHCI_TRB_SLOT_SHIFT 24
#define XHCI_TRB_SLOT_TYPE_SHIFT 16
#define XHCI_TRB_LINK 6
#define XHCI_TRB_ENABLE_SLOT 9
#define XHCI_TRB_DISABLE_SLOT 10
#define XHCI_EVENT_COMMAND 33
#define XHCI_EVENT_PORT 34
#define XHCI_EVENT_COMPLETION_SHIFT 24
#define XHCI_EVENT_SUCCESS 1
#define XHCI_EVENT_PORT_SHIFT 24
#define XHCI_RING_ALIGNMENT 64
#define XHCI_RING_BOUNDARY 65536
#define XHCI_ERST_BYTES 16

#endif
