#ifndef USB_SETTINGS_H
#define USB_SETTINGS_H

/* Initial resource/deadline choices, independent of image and machine sizes. */
#define USB_STATE_TIMEOUT_MS 1000
#define USB_COMMAND_TIMEOUT_MS 5000
#define USB_CONTROL_TIMEOUT_MS 5000
#define USB_ENUMERATION_TIMEOUT_MS 30000
#define USB_PORT_POWER_DELAY_MS 20
#define USB_WORKER_POLL_MS 10
#define USB_CONTROL_BYTES 4096
#define USB_BULK_BYTES 65536
#define USB_STORAGE_DEVICE_BUDGET 4
#define USB_ASYNC_BULK_DEVICE_BUDGET 1
#define USB_ASYNC_BULK_BYTES 4096
#define USB_ASYNC_BULK_RECEIVES 2
#define USB_ASYNC_BULK_COMPLETIONS 8
/* Maximum HCI event: two header bytes plus 255 parameter bytes. */
#define USB_INTERRUPT_BYTES 257
#define USB_HID_DEVICE_BUDGET 32
#define USB_HID_ENDPOINTS_PER_DEVICE 2
#define USB_HUB_INTERRUPT_DEVICE_BUDGET 32
#define USB_INTERRUPT_RECEIVES 2
#define USB_INTERRUPT_COMPLETIONS 8
#define USB_BOT_TIMEOUT_MS 5000
#define USB_BOT_RECOVERY_TIMEOUT_MS 5000
#define USB_INTERFACE_BUDGET 512
#define USB_DESCENDANT_BUDGET 32
#define USB_HUB_POLL_MS 10
#define USB_HUB_DEBOUNCE_MS 100
#define USB_HUB_RESET_TIMEOUT_MS 1000
#define USB_HUB_RESET_RECOVERY_MS 10

#endif
