name: Build Pyxis

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  image:
    runs-on: pyxis
    container:
      image: git.internal/chronium/pyxis-builder:pyxis-gcc16.2-binutils2.47
      credentials:
        username: chronium
        password: ${{ secrets.PYXIS_REGISTRY_READ_TOKEN }}
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PYXIS_SOURCE_READ_TOKEN }}
          persist-credentials: false
      - name: Build bootable ISO
        run: make -j4 image
      - name: Save kernel and ISO
        uses: https://data.forgejo.org/actions/upload-artifact@v3
        env:
          NODE_USE_SYSTEM_CA: '1'
        with:
          name: pyxis-image
          path: |
            build/pyxis.iso
            build/caelum.elf
          if-no-files-found: error
