OUTPUT_FORMAT(elf64-x86-64)
ENTRY(_start)
PHDRS {
  text PT_LOAD FLAGS(5);
  rodata PT_LOAD FLAGS(4);
  data PT_LOAD FLAGS(6);
}
SECTIONS {
  . = 0xffffffff80000000;
  __kernel_start = .;
  __text_start = .;
  .text : { *(.text .text.*) } :text
  . = ALIGN(4096);
  __text_end = .;
  __rodata_start = .;
  .rodata : { *(.rodata .rodata.*) } :rodata
  . = ALIGN(4096);
  __rodata_end = .;
  __data_start = .;
  .limine_requests : {
    KEEP(*(.limine_requests_start))
    KEEP(*(.limine_requests))
    KEEP(*(.limine_requests_end))
  } :data
  .data : { *(.data .data.*) } :data
  .bss : { *(.bss .bss.*) *(COMMON) } :data
  . = ALIGN(4096);
  __data_end = .;
  __kernel_end = .;
  /DISCARD/ : { *(.eh_frame*) *(.note .note.*) *(.comment) }
}
