#ifndef ABI_KEY_H
#define ABI_KEY_H

/* Key positions use common PC legends; these are not characters or scan codes. */
enum key_code {
  KEY_NONE,
  KEY_ESCAPE,
  KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6,
  KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12,
  KEY_GRAVE,
  KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
  KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_TAB,
  KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,
  KEY_LEFT_BRACKET, KEY_RIGHT_BRACKET, KEY_BACKSLASH,
  KEY_CAPS_LOCK,
  KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
  KEY_SEMICOLON, KEY_APOSTROPHE, KEY_ENTER,
  KEY_LEFT_SHIFT, KEY_NON_US_BACKSLASH,
  KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M,
  KEY_COMMA, KEY_PERIOD, KEY_SLASH, KEY_RIGHT_SHIFT,
  KEY_LEFT_CONTROL, KEY_LEFT_SUPER, KEY_LEFT_ALT, KEY_SPACE,
  KEY_RIGHT_ALT, KEY_RIGHT_SUPER, KEY_MENU, KEY_RIGHT_CONTROL,
  KEY_PRINT_SCREEN, KEY_SCROLL_LOCK, KEY_PAUSE,
  KEY_INSERT, KEY_HOME, KEY_PAGE_UP, KEY_DELETE, KEY_END, KEY_PAGE_DOWN,
  KEY_UP, KEY_LEFT, KEY_DOWN, KEY_RIGHT,
  KEY_NUM_LOCK, KEY_KP_DIVIDE, KEY_KP_MULTIPLY, KEY_KP_MINUS, KEY_KP_PLUS,
  KEY_KP_0, KEY_KP_1, KEY_KP_2, KEY_KP_3, KEY_KP_4,
  KEY_KP_5, KEY_KP_6, KEY_KP_7, KEY_KP_8, KEY_KP_9,
  KEY_KP_PERIOD, KEY_KP_ENTER,
  KEY_COUNT,
};

enum key_action {
  KEY_PRESS,
  KEY_RELEASE,
  KEY_REPEAT,
  KEY_STATE_RESET,
  KEY_FOCUS_GAINED,
  KEY_FOCUS_LOST,
};

enum key_modifiers {
  KEY_MOD_SHIFT = 1u << 0,
  KEY_MOD_CONTROL = 1u << 1,
  KEY_MOD_ALT = 1u << 2,
  KEY_MOD_SUPER = 1u << 3,
  KEY_MOD_CAPS_LOCK = 1u << 4,
  KEY_MOD_NUM_LOCK = 1u << 5,
  KEY_MOD_SCROLL_LOCK = 1u << 6,
};

#endif
