#ifndef ABI_MESSAGE_H
#define ABI_MESSAGE_H

#include <stdint.h>

#define PROTOCOL_CONSOLE UINT64_C(1)
#define PROTOCOL_FILE UINT64_C(2)
#define PROTOCOL_ENDPOINT UINT64_C(3)
#define PROTOCOL_DIRECTORY UINT64_C(4)
#define PROTOCOL_MEMORY UINT64_C(5)
#define PROTOCOL_PROCESS UINT64_C(6)
#define PROTOCOL_LAUNCHER UINT64_C(7)
#define PROTOCOL_DISPLAY UINT64_C(8)
#define PROTOCOL_CLOCK UINT64_C(9)
#define PROTOCOL_KEYBOARD UINT64_C(10)
#define PROTOCOL_MOUNT UINT64_C(11)
#define PROTOCOL_ECHO UINT64_C(12)
#define PROTOCOL_NET_CONFIG UINT64_C(13)
#define PROTOCOL_UDP_SERVICE UINT64_C(14)
#define PROTOCOL_UDP UINT64_C(15)
#define PROTOCOL_RANDOM UINT64_C(16)

#define PROTOCOL_TCP_SERVICE UINT64_C(17)
#define PROTOCOL_TCP UINT64_C(18)
#define PROTOCOL_SPACE UINT64_C(19)
#define PROTOCOL_PROFILE UINT64_C(20)
#define PROTOCOL_PIPE_SERVICE UINT64_C(21)
#define PROTOCOL_PIPE UINT64_C(22)

#define PROTOCOL_ENDPOINT_SERVICE UINT64_C(23)
#define PROTOCOL_ENDPOINT_RECEIVER UINT64_C(24)
#define PROTOCOL_ENDPOINT_RECEIPT UINT64_C(25)

#define PROTOCOL_NAMESPACE_SERVICE UINT64_C(27)
#define PROTOCOL_NAMESPACE UINT64_C(28)
#define PROTOCOL_PROVIDER UINT64_C(29)
#define PROTOCOL_TCP_LISTENER UINT64_C(30)
#define PROTOCOL_TERMINAL_SERVICE UINT64_C(31)
#define PROTOCOL_TERMINAL_ATTACHMENT UINT64_C(32)
#define PROTOCOL_EXECUTION_GROUP UINT64_C(33)
#define PROTOCOL_TERMINAL_EVENTS UINT64_C(34)
#define PROTOCOL_SYSTEM_INFO UINT64_C(35)

/* The handle selects the object; this tag identifies the request protocol,
 * never the caller's authority. Operation numbers are local to that protocol. */
struct message_header {
  uint64_t protocol;
  uint64_t operation;
};

_Static_assert(sizeof(struct message_header) == 16, "message header layout");

#endif
