#ifndef KERNEL_PCI_REGISTERS_H
#define KERNEL_PCI_REGISTERS_H

#include <stdint.h>

#define PCI_VENDOR_ID 0x00
#define PCI_DEVICE_ID 0x02
#define PCI_STATUS 0x06
#define PCI_REVISION 0x08
#define PCI_INTERFACE 0x09
#define PCI_SUBCLASS 0x0a
#define PCI_CLASS 0x0b
#define PCI_HEADER_TYPE 0x0e
#define PCI_BAR_FIRST 0x10
#define PCI_BRIDGE_PRIMARY 0x18
#define PCI_BRIDGE_SECONDARY 0x19
#define PCI_BRIDGE_SUBORDINATE 0x1a
#define PCI_CAPABILITIES 0x34

#define PCI_NO_VENDOR UINT16_MAX
#define PCI_STATUS_CAPABILITIES (1u << 4)
#define PCI_HEADER_MULTIFUNCTION (1u << 7)
#define PCI_HEADER_TYPE_MASK 0x7f
#define PCI_HEADER_ENDPOINT 0
#define PCI_HEADER_BRIDGE 1
#define PCI_ENDPOINT_BARS 6
#define PCI_BRIDGE_BARS 2
#define PCI_REGISTER_BYTES 4
#define PCI_BAR_IO 1u
#define PCI_BAR_MEMORY_TYPE_MASK 6u
#define PCI_BAR_MEMORY_32 0u
#define PCI_BAR_MEMORY_64 4u
#define PCI_BAR_PREFETCHABLE 8u
#define PCI_BAR_IO_ADDRESS_MASK (~UINT32_C(3))
#define PCI_BAR_MEMORY_ADDRESS_MASK (~UINT32_C(15))
#define PCI_BAR_HIGH_SHIFT 32
#define PCI_CLASS_BRIDGE 0x06
#define PCI_SUBCLASS_PCI_BRIDGE 0x04

#define PCI_CONVENTIONAL_BYTES 256
#define PCI_CAP_FIRST 0x40
#define PCI_CAP_POINTER_MASK 0xfc
#define PCI_CAP_ID 0
#define PCI_CAP_NEXT 1
#define PCI_CAP_POWER 0x01
#define PCI_CAP_MSI 0x05
#define PCI_CAP_VENDOR 0x09
#define PCI_CAP_EXPRESS 0x10
#define PCI_CAP_MSIX 0x11
#define PCI_EXT_CAP_FIRST 0x100
#define PCI_EXT_CAP_ID_MASK 0xffff
#define PCI_EXT_CAP_VERSION_SHIFT 16
#define PCI_EXT_CAP_VERSION_MASK 0xf
#define PCI_EXT_CAP_NEXT_SHIFT 20

#define PCI_COMMAND 0x04
#define PCI_COMMAND_IO 1u
#define PCI_COMMAND_MEMORY 2u
#define PCI_COMMAND_MASTER 4u
#define PCI_COMMAND_INTX_DISABLE (1u << 10)
#define PCI_EXPRESS_LINK_CONTROL 0x10
#define PCI_EXPRESS_LINK_BYTES 0x12
#define PCI_EXPRESS_LINK_ASPM 3u
#define PCI_EXPRESS_LINK_CLKREQ (1u << 8)
#define PCI_POWER_BYTES 8
#define PCI_POWER_CONTROL 4
#define PCI_POWER_STATE_MASK 3u
#define PCI_POWER_D0 0u
#define PCI_POWER_D3HOT 3u
#define PCI_POWER_NO_SOFT_RESET (1u << 3)
#define PCI_POWER_PME_ENABLE (1u << 8)
#define PCI_POWER_DATA_SELECT_MASK (15u << 9)
#define PCI_POWER_PME_STATUS (1u << 15)
#define PCI_POWER_CONTROL_WRITABLE (PCI_POWER_STATE_MASK | PCI_POWER_PME_ENABLE | \
                                    PCI_POWER_DATA_SELECT_MASK)
#define PCI_MSI_CONTROL 2
#define PCI_MSI_ENABLE 1u
#define PCI_MSIX_CONTROL 2
#define PCI_MSIX_TABLE 4
#define PCI_MSIX_PBA 8
#define PCI_MSIX_BYTES 12
#define PCI_MSIX_ENABLE (1u << 15)
#define PCI_MSIX_FUNCTION_MASK (1u << 14)
#define PCI_MSIX_SIZE_MASK 0x7ffu
#define PCI_MSIX_BAR_MASK 7u
#define PCI_MSIX_OFFSET_MASK (~UINT32_C(7))
#define PCI_MSIX_ENTRY_BYTES 16u
#define PCI_MSIX_VECTOR_MASK 1u
#define PCI_MSIX_PBA_BITS 64u
#define PCI_MSIX_PBA_WORD_BYTES 8u

#endif
