# PYXIS_BOOT_MENU_TIMEOUT
serial: yes

/Pyxis OS (Caelum)
  protocol: limine
  path: boot():/boot/caelum.elf
  module_path: boot():/boot/initrd.cpio
  paging_mode: 4level
  kaslr: no
# PYXIS_NORMAL_COMMAND_LINE

/Install Pyxis
  protocol: limine
  path: boot():/boot/caelum.elf
  module_path: boot():/boot/initrd.cpio
  paging_mode: 4level
  kaslr: no
  cmdline: space.install=boot://init-install.pxe boot.install=1
